"""
Updates made by: Alexander Kedrowitsch <alexk1@vt.edu>

Aggregate changes for commits in range: 20247a4..275be8c

Modified/Added Function: build
  - Related commit message: ltp-protocol-test.cc has a functional bit vector queue to send multiple vectors via LTP

"""
# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('ltp-protocol-example', ['ltp-protocol', 'core', 'internet', 'network', 'point-to-point'])
    obj.source = 'ltp-protocol-example.cc'

    obj = bld.create_ns3_program('ltp-protocol-long-transmission-example', ['ltp-protocol', 'core', 'internet', 'network', 'point-to-point','flow-monitor'])
    obj.source = 'ltp-protocol-long-transmission-example.cc'
    
    obj = bld.create_ns3_program('ltp-protocol-test', ['ltp-protocol', 'core', 'internet', 'network', 'point-to-point'])
    obj.source = 'ltp-protocol-test.cc'


